name: Deploy RSBIZ to GoDaddy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

            - name: Deploy to GoDaddy
        uses: step-security/ftp-deploy-action@v4
        with:
          server: 198.12.246.102
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          server-dir: ./
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/node_modules/**
